#!/bin/bash
while read line
do
    echo '<!--raspberry pi apache2 webserver setup: hosted as index.html -->'
    echo '<!DOCTYPE html>'
    echo '<html>'
    echo '	<head>'
    echo '		<meta name="google-site-verification" content="8kJsSKnInRQzx6_yw-gaE2O3MUJWu5nEsFnCAReZvPw" />'
    echo '		<meta charset="utf-8">'
    echo '		<title>HomeBot</title>'
    echo '		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>'
    echo '		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJwpqZPH0R-gFOIJXjomi-tPpecCBCS5U"></script>'
    echo '	</head>'
    echo '	<body>'
    echo '      <div id="output">This text will be replaced with information from the data.php script after an JSON call to the script</div>'
    echo '		<div id="map"></div>'
    echo '		<script type="text/javascript">'
    echo '		//Setting Value of Homebot'
    echo '		var homebot=new google.maps.LatLng('
    echo '			//GeoLocation from server'
    echo '		)'
    echo '		var phone=new google.maps.LatLng('
    echo 			$line
    echo '		)'
    echo '		var markerPhone;'
    echo '		var markerHomebot;'
    echo '		function initialize(){'
    echo '			var mapProp = {  center:markerHomebot,  zoom:15,  mapTypeId:google.maps.MapTypeId.ROADMAP};'
    echo '			var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);'
    echo '			markerHomebot=new google.maps.Marker({'
    echo '				position:homebot,'
    echo '				//animation:google.maps.Animation.BOUNCE'
    echo '				title: "HomeBot"'
    echo '			});'
    echo '			markerHomebot.setMap(map);'			
    echo '			//Add circle overlay and bind to marker'
    echo '			var greenCircle=new google.maps.Circle({'
    echo '				map: map,'
    echo '				radius: 1000,    //1000 metres'
    echo '				fillColor: "#00cc00"'
    echo '			});'    
    echo '			greenCircle.bindTo("center", markerHomebot, "position");'
    echo '			var yellowCircle=new google.maps.Circle({'
    echo '	  			map: map,'
    echo '	  			radius: 500,    //500 metres'
    echo '	  			fillColor: "#ffcc00"'
    echo '			});'
    echo '			yellowCircle.bindTo("center", markerHomebot, "position");'
    echo '			var redCircle=new google.maps.Circle({'
    echo '	  			map: map,'
    echo '	  			radius: 100,    //100 metres'
    echo '	  			fillColor: "#AA0000"'
    echo '			});'
    echo '			redCircle.bindTo("center", markerHomebot, "position");'
    echo '			var infoWindow = new google.maps.InfoWindow({map: map});'
    echo '	        	// Try HTML5 distance.'
    echo '			var rad = function(x) {'
    echo '				return x * Math.PI / 180;'   
    echo '			};'
    echo '			var getDistance = function(homebot, phone) {'
    echo '				var R = 6378137; // Earth’s mean radius in meter'
    echo '			  	var dLat = rad(phone.lat() - homebot.lat());'
    echo '			  	var dLong = rad(phone.lng() - homebot.lng());'
    echo '				var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +'
    echo '				Math.cos(rad(homebot.lat())) * Math.cos(rad(phone.lat())) *'
    echo '				Math.sin(dLong / 2) * Math.sin(dLong / 2);'
    echo '			  	var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));'
    echo '			  	var d = R * c;'
    echo '			  	return d; //returns the distance in meter'
    echo '			};'
    echo '			if (getDistance(homebot, phone) < 100){'
    echo '				console.log("Code Red");'
    echo '				//$.get("enablemotion.php");'
    echo '				console.log(getDistance(homebot, phone));'
    echo '				//its a Loop...'
    echo '				$(function (){'
    echo '                  			$.ajax({'
    echo '                     				url: "https://homeautomationbot.ddns.net/enableserver.php",'
    echo '                      			data: "name=Server starts:",'
    echo '                      			dataType: "json",'
    echo '                      			success: function(data)'
    echo '                      			{'
    echo '                          				$("#output").html(data);'
    echo '                      			} ,'
    echo '                      			error: function()'
    echo '                      			{'
    echo '                          				$("#output").html("Error");'
    echo '                      			}'
    echo '                  			});'
    echo '              		});'
    echo ' 				if (window.location.href == "https://homeautomationbot.ddns.net"){'
    echo '					//window.location = "https://homeautomationbot.ddns.net/#?motion=true";'
    echo '				}else{'
    echo '					//window.location.href = "https://homeautomationbot.ddns.net/#?motion=true";'
    echo '				}'
    echo '			}else if(getDistance(homebot, phone) > 101 && getDistance(homebot, phone) < 499){'
    echo '				console.log("Code Yellow");'
    echo '				console.log(getDistance(homebot, phone));'
    echo '				$(function (){'
    echo '                  			$.ajax({'
    echo '                     				url: "https://homeautomationbot.ddns.net/enablemotion.php",'
    echo '                      			data: "name=motion starts:",'
    echo '                      			dataType: "json",'
    echo '                      			success: function(data)'
    echo '                      			{'
    echo '                          				$("#output").html(data);'
    echo '                      			} ,'
    echo '                      			error: function()'
    echo '                      			{'
    echo '                          				$("#output").html("Error");'
    echo '                      			}'
    echo '                  			});'
    echo '              		});'
    echo ' 				if (window.location.href == "https://homeautomationbot.ddns.net/#?motion=true"){'
    echo '					//window.location.href = "https://homeautomationbot.ddns.net/#?motion=false";'
    echo '				}else{'
    echo '					//window.location.href = "https://homeautomationbot.ddns.net";'
    echo '				}'
    echo '			}else{'
    echo '				console.log("Code green");'
    echo '				console.log(getDistance(homebot, phone));'
    echo '				$(function (){'
    echo '                  			$.ajax({'
    echo '                     				url: "https://homeautomationbot.ddns.net/disablemotion.php",'
    echo '                      			data: "name=motion stops:",'
    echo '                      			dataType: "json",'
    echo '                      			success: function(data)'
    echo '                      			{'
    echo '                          				$("#output").html(data);'
    echo '                      			} ,'
    echo '                      			error: function()'
    echo '                      			{'
    echo '                          				$("#output").html("Error");'
    echo '                      			}'
    echo '                  			});'
    echo '              		});'
    echo '			}'
    echo '	            	infoWindow.setPosition(phone);'
    echo '	       		infoWindow.setContent("You are here.");'
    echo '	       		map.setCenter(phone);'
    echo '		}'
    echo '		google.maps.event.addDomListener(window, "load", initialize);'
    echo '		//Uncomment, if reload is necessary'
    echo '		//setTimeout(function(){window.location.reload(1);}, 10000);'
    echo '		</script>'
    echo '		<div id="googleMap" style="width:1024px;height:600px;"></div>'
    echo '	</body>'
    echo '</html>'
done